### ISSUE TITLE
qustion

### ISSUE THREAD

**Issue by Louisspitz** [KYDronePilot/hdfm#12]
could you create a zip file with it already compiled.

**Comment by KYDronePilot** [comment]
Is this for a Windows, Linux, or Mac OS? I would eventually like to release the program as a package, but at the moment, I'm not sure if I'll have the time to do it.

**Comment by KYDronePilot** [comment]
On a side note, if you happen to be running Windows, I could use your help beta testing an updated version of the program.

I've rewrote all the code and added a lot of features under the "refactor" branch of this project, but I haven't been able to test it on Windows yet. So far, there have been no issues with Mac or Linux.

If you run Windows and are interested, please get back to me.

**Comment by rd0fun** [comment]
I tried (what I think) is this branch on a Mac with no luck. make dies on ".env".

**Comment by KYDronePilot** [comment]
Latest release includes prebuilt binaries for Windows, Mac, and Linux: https://github.com/KYDronePilot/hdfm/releases/latest. Let me know if you run into any issues with them.
