### ISSUE TITLE
Windows Solution/WSL2

### ISSUE THREAD

**Issue by ferrellsl** [KYDronePilot/hdfm#21]
Hi.  Nice work.  I'm really enjoying your app.  I ran into the same problem with the permissions error as a couple other folks when trying to run this under Windows.  Whether running it under MSYS2 or python for Windows  I'd always get the same permissions error.  

I decided to give WSL2 a shot and got it working quite well.  In order to get the app to work in WSL2 I had to edit line 307 of the gui.py file located in the hdfm/src directory.  I have the nrsc5.exe and the libnrsc5.dll located on my D: drive in a folder called nrsc5.  So, I modified line 307 to read:   '/mnt/d/nrsc5/nrsc5.exe'

For users who have the nrsc5.exe in different location, just change the above to match the correct folder location.  WSL2 accesses the Windows file system using the path /mnt/c for the C: drive and /mnt/d for the D: drive and so on, so just append the correct path to the /mnt/ and you'll have no problems.

![image](https://user-images.githubusercontent.com/5926287/155009090-89181f6a-ab7a-4bb5-a01e-1b1f6777c9df.png)

**Comment by KYDronePilot** [comment]
I guess this is no longer applicable since hdfm has been rewritten in Rust. Thanks for providing the info though; didn't know the old version was runnable through WSL.
