### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ferrellsl** [KYDronePilot/hdfm#22]
Just wanted to say thanks for the 2.0 release.  Now there's no need for complicated python installations or virtual machines running Linux for Windows users.  The 2.0 release works great for me.  Keep up the good work!

**Comment by KYDronePilot** [comment]
Glad it's working well for you and thanks for your support!

**Comment by bmn001** [comment]
Confirming here on this closed bug, rather than opening a new one, this does seem to work just fine with Linux.  Ubuntu 22.04 over here, no problems.  Thanks!

**Comment by KYDronePilot** [comment]
Thanks, glad to hear it!
