### ISSUE TITLE
Add list of known iHeartRadio stations that work

### ISSUE THREAD

**Issue by vielmetti** [KYDronePilot/hdfm#7]
I'm tuning through the Detroit/Ann Arbor Michigan stations and not finding traffic and weather just yet. It would be good to add a list of stations that are known to work with this system.

**Comment by KYDronePilot** [comment]
Sure thing. Here's a list of all radio stations run by iHeartRadio (https://en.wikipedia.org/wiki/List_of_radio_stations_owned_by_iHeartMedia). It is possible that other stations broadcast weather and traffic data in different formats, which could be what's causing the issue. In that case, check the dump directory and see if it's being populated with files. I'll go ahead and add the link above to the readme.

**Comment by vielmetti** [comment]
I got a good decode of traffic in the Detroit area from 95.5 FM!

![image](https://user-images.githubusercontent.com/35047/34280889-e0cb21e8-e688-11e7-9af5-a8d1c51a5d68.png)

**Comment by KYDronePilot** [comment]
That's great! Glad to have visual proof that it works outside of my region. Were you able to get a weather decode as well? Sometimes it can take longer than the traffic decode.

**Comment by n8dgr8** [comment]
Just picked up some weather maps and traffic off of iHeart stations (106.3, specifically) here in DSM, IA!  Thanks for making this, it is really fun!  😄

**Comment by KYDronePilot** [comment]
No problem and thank you for using it! Glad everything is working on your end. If you have any recommendations for improvements, leave a comment and I'll see what I can do.
