### ISSUE TITLE
Not saving any images

### ISSUE THREAD

**Issue by zachnoren** [KYDronePilot/hdfm#8]
Hi I'm not able to get this to save any images, and I am not receiving any errors either. I believe I installed all the necessary libraries correctly. Here is some output from my terminal below. I have tried some debugging on my own. I really want this to work it seems very cool.

`20:29:21 INFO  sync.c:332: MER: 15.3 dB (lower), 15.5 dB (upper)
20:29:21 INFO  decode.c:77: BER: 0.000000, avg: 0.000000, min: 0.000000, max: 0.000000
20:29:21 DEBUG output.c:384: Title: Praise 106.1
20:29:21 DEBUG output.c:390: Artist:
20:29:21 DEBUG output.c:384: Title: Praise 106.1
20:29:21 DEBUG output.c:390: Artist:
20:29:21 DEBUG output.c:384: Title: Praise 106.1
20:29:21 DEBUG output.c:390: Artist:
20:29:21 DEBUG output.c:129: Audio bit rate: 14.9 kbps
traffic save
traffic save
traffic save
20:29:22 INFO  sync.c:332: MER: 15.4 dB (lower), 15.5 dB (upper)
20:29:22 INFO  decode.c:77: BER: 0.000000, avg: 0.000000, min: 0.000000, max: 0.000000
20:29:22 INFO  output.c:634: Received SLWLIF$$010001.jpg, port 0411
20:29:22 DEBUG output.c:384: Title: Praise 106.1
20:29:22 DEBUG output.c:390: Artist:
20:29:22 DEBUG output.c:384: Title: Praise 106.1
20:29:22 DEBUG output.c:390: Artist:
20:29:22 DEBUG output.c:129: Audio bit rate: 14.4 kbps
traffic save
traffic save
traffic save
20:29:24 INFO  sync.c:332: MER: 15.3 dB (lower), 15.4 dB (upper)
20:29:24 INFO  decode.c:77: BER: 0.000000, avg: 0.000000, min: 0.000000, max: 0.000000
20:29:24 DEBUG output.c:595: 00000001 7EBC9CE4 1E653E9C
20:29:24 INFO  output.c:619: File SLWLIF$$010001.jpg, size 9785, port 0411
20:29:24 INFO  frame.c:308: psd crc mismatch
20:29:24 DEBUG output.c:384: Title: PRAISE 106.1
20:29:24 DEBUG output.c:390: Artist:
20:29:24 DEBUG output.c:384: Title: PRAISE 106.1
20:29:24 DEBUG output.c:390: Artist:
20:29:24 DEBUG output.c:129: Audio bit rate: 15.1 kbps
traffic save
traffic save
traffic save`

**Comment by KYDronePilot** [comment]
Could you post a copy of the command you’re running?

**Comment by zachnoren** [comment]
python3.6 ./hdfm.py -s . -l 1 -c 1 101.9

**Comment by zachnoren** [comment]
Hey! It just worked! Looks like the stations in my area are just hit or miss. Totally awesome!

**Comment by KYDronePilot** [comment]
Thanks! I think your problem was that the station wasn't run by iHeartRadio. Here's a list of all iHeartRadio stations nationwide: https://en.wikipedia.org/wiki/List_of_radio_stations_owned_by_iHeartMedia
