### ISSUE TITLE
Something is missing?

### ISSUE THREAD

**Issue by DaveNF2G** [KYDronePilot/hdfm#9]
I am trying to use HDFM under Windows 10x64 Pro on an Intel i7 quad core processor.  I have no wish to become a Python programmer and I never attended Hogwarts.  There seems to be a lot of obscurity in the Python use process.   Here is what I get when I try to execute HDFM after having installed Pillow successfully.  NRSC5.exe is also present.  The folders for NRSC5 and hdfm.py are in the system path.  Despite that, I have to specify the path to hdfm.py or Python can't find it.  

What else can't Windows or Python find?  Several files are referenced  in the Traceback, but the "not found" message is totally nonspecific.

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>python c:\hdfm\hdfm.py 103.1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\HPWindows7\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\HPWindows7\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\hdfm\hdfm.py", line 60, in startNRSC5
    "--dump-aas-files", dump_dir, freq, channel])
  File "C:\Users\HPWindows7\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\HPWindows7\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\HPWindows7\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by KYDronePilot** [comment]
hdfm was developed with only Mac and Linux operating systems in mind. I haven't tried porting it over to Windows yet, do to hardware limitations on my end. My Windows OS runs in a VM and nrsc5 doesn't like the extra latency. I'll look into a solution in the coming week and if found, I'll try to port hdfm over to windows.

**Comment by markm76017** [comment]
I am also using Windows 10.  HDFM works putting the traffic tiles in their proper place, but gives me this error once I see the first DWRI file in the Dump directory.

C:\Users\markm\Documents\airspy\HDRadio\nrsc5>hdfm.py -c0 =p2 92.5 >> hdfm_test
Found Rafael Micro R820T tuner
Exact sample rate is: 1488375.071248 Hz
[R82XX] PLL not locked!
Traceback (most recent call last):
  File "C:\Users\markm\Documents\airspy\HDRadio\nrsc5\hdfm.py", line 240, in <module>
    weather_final = Image.alpha_composite(
AttributeError: 'module' object has no attribute 'alpha_composite'

**Comment by markm76017** [comment]
got everything working by reinstalling PILLOW Pillow-5.0.0

**Comment by KYDronePilot** [comment]
Glad that fixed it for you. I'm surprised it works on windows at all since I designed the program entirely on a mac. Did you have to make any changes to the original code?

**Comment by markm76017** [comment]
I did not have to change the code, although I did add some print statements to see the names of variables.  The problem was one of the libraries was not compiled into the PILLOW I was originally using.  I found some comments on the Internet about similar problems and that let me to the PILLOW package that i needed.  https://www.lfd.uci.edu/~gohlke/pythonlibs/

I am going to try a Rasberry Pi next.

**Comment by markm76017** [comment]
The wheel package I used was Pillow‑5.0.0‑cp37‑cp37m‑win32.whl

**Comment by markm76017** [comment]
Got it working on a Rasberry Pi 3 B + Running Raspbian Stretch with desktop
Image with desktop based on Debian Stretch
Version: March 2018
Release date: 2018-03-13
Kernel version: 4.9

**Comment by KYDronePilot** [comment]
Thank you for posting the link. I have updated the readme to include the link to this page. Glad to hear it's working on the new B+. Please let me know if you have any other problems.
